# ==============================
# LOCAL (Eclipse + MySQL)
# ==============================
spring.application.name=food-delivery-app

# MySQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.jackson.serialization.fail-on-empty-beans=false


# Server
server.port=${PORT:8080}
# Thymeleaf
spring.thymeleaf.cache=false
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web.servlet.PageNotFound=WARN


# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.fooddelivery=DEBUG

#spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true
# spring.web.resources.add-mappings=false 

# Custom error pages path
server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-exception=false

